version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.prod
    volumes:
      - ./db/devices.sql:/docker-entrypoint-initdb.d/devices.sql
    ports:
      - "5432:5432"
    networks:
      - stack
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules/
    depends_on:
      - db
    networks:
      - stack

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules/
    networks:
      - stack
networks:
  stack:
